### PR TITLE
Home: Small Changes for home-desk-apx.svg

### PR DESCRIPTION
**Pull request by GabsEdits**
#### Changed the image `home-desk-apx.svg` to adapt how the Team recommends using ABRoot:
* I've added `sudo` to  the start to represent that you need to be a `super-user` to use it.
* Instead of `nice-stuff` it's now `nice-drivers`, it's heavily recommended by the Team to use ABRoot `exec` command only to install a needed driver.

**This Pull Request was made thanks to:** [The Discord Community](https://discord.gg/3cD2Q7Ht3S)

### CODE REVIEW

**Comment by MonsterObserver** [comment]
A couple things here:
- The image shifted to the right
- The font changed
- We should probably reserve this for 2.0 since this behavior might change

**Comment by axtloss** [comment]
The new font is not suited in this case since it's not a monospace font, which also reduces the readability of the text, not to mention that it is too small now.

**Comment by GabsEdits** [comment]
> The new font is not suited in this case since it's not a monospace font, which reduces the readability of the text, not to mention that it is too small.

Can I get the original font?

**Comment by GabsEdits** [comment]
The Fonts are a bit messy. I will close this Pull Request.

**Comment by mirkobrombin** [comment]
You need to vectorize the text

**Comment by GabsEdits** [comment]
> You need to vectorize the text

Thanks @mirkobrombin , now I've done that. I think the image now looks right

**Comment by mirkobrombin** [comment]
which is it?

**Comment by GabsEdits** [comment]
> which font is it?

The Font used is "SF Mono"

**Comment by mirkobrombin** [comment]
Can you switch to Fira Code?

**Comment by GabsEdits** [comment]
> Can you switch to Fira Code?

Sure, will do that

**Comment by GabsEdits** [comment]
Font Updated :D

**Pull request merged**
