### PR TITLE
A real All-in-One Contributors List across the Organization

### PR DESCRIPTION
**Pull request by GabsEdits**
So, I've made a list of all Contributors across the Organization. I've made a script that get all repos and it's contributors, then I got that and made another script that made sure there is no duplication. And then added a counter and saw the result, with that I've made the Markdown file in our classic "Vanilla README" way. And the title supports dark & light mode of course.

I've started this when I saw on the "Team" page this text: "There are many more people who have contributed to Vanilla OS. See the <a href="https://github.com/orgs/Vanilla-OS/people">full list of contributors</a>." and the GitHub "People" page only showed the Members. So I've made this. The File is automatically updated every week using GitHub CI.

* You can preview the big 131 unique contributors list here as an image:

image

### CODE REVIEW

**Comment by pulkitkrishna00** [comment]
It would be cool to use Github CI to update the page automatically. Also, it would be better to have the names of contribution link to their github profile, I think it can be scripted.

**Review by mirkobrombin — APPROVED** [review]

**Comment by alinpr18** [comment]
Would be nice, introduce colaboratos on a table, example:

| autor | github | Example |
|--------|--------|--------|
| Ali Paredes | alinpr18 | Example |

**Comment by kbdharun** [comment]
> Would be nice, introduce contributors on a table, example:

Indeed but I don't know if it will be rendered on the website with our custom CSS

Also, how about using https://allcontributors.org/ bot like [Gaphor](https://github.com/gaphor/gaphor) and other popular projects

**Comment by GabsEdits** [comment]
> Indeed but I don't know if it will be rendered on the website with our custom CSS

I've made it as a GitHub view markdown file, but I can try to make it work 😅

**Comment by GabsEdits** [comment]
> Also, how about using https://allcontributors.org/ bot like [Gaphor](https://github.com/gaphor/gaphor) and other popular projects

That sounds interesting, maybe we can use a bot that you can ask to be added to the list?

**Comment by GabsEdits** [comment]
I've marked as draft since I have to work with GitHub CI.

**Review by kbdharun — APPROVED** [review]

**Comment by GabsEdits** [comment]
> It would be cool to use Github CI to update the page automatically. Also, it would be better to have the names of contribution link to their github profile, I think it can be scripted.

Me and @kbdharun successfully fixed & added everything. The File automatically updates every week, all the users have links to their profile.

**Comment by kbdharun** [comment]
> Is this ready to be merged?

Yes

**Comment by GabsEdits** [comment]
> Is this ready to be merged?

Ready

**Pull request merged**
