### PR TITLE
feat: add prettier

### PR DESCRIPTION
**Pull request by GabsEdits**

### CODE REVIEW

**Review by kbdharun — COMMENTED** [review]
This workflow wouldn't work unfortunately since the default branch has branch protection so any automated commits using the GitHub actions account will be blocked.

**Comment by GabsEdits** [comment]
> This workflow wouldn't work unfortunately since the default branch has branch protection so any automated commits using the GitHub actions account will be blocked.

Could we potentially whitelist the Actions user from the branch protection?

**Comment by kbdharun** [comment]
> Could we potentially whitelist the Actions user from the branch protection?

Nope, that isn't possible, checkout https://github.com/orgs/community/discussions/25305.

**Comment by GabsEdits** [comment]
> > Could we potentially whitelist the Actions user from the branch protection?
> 
> Nope, that isn't possible, checkout https://github.com/orgs/community/discussions/25305.

I guess I will remove the workflow, and just leave it as a script for NPM

**Review by kbdharun — APPROVED** [review]

**Review by mirkobrombin — APPROVED** [review]

**Pull request merged**
