### PR TITLE
Fixed a mistake where media icon colours were inverted twice in dark mode

### PR DESCRIPTION
**Pull request by OpenSauce04**
This meant that the colour of the icons would not change

### CODE REVIEW

**Comment by OpenSauce04** [comment]
I did this by accident in my last PR because I forgot that CSS `filter` properties stack instead of replacing the previous filter

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution. Nice catch by the way.

For others to refer to, this is the comparison.

Current

image


This PR

image

**Comment by mirkobrombin** [comment]
imho they are both hard to read

**Comment by kbdharun** [comment]
> imho they are both hard to read

Agreed, maybe normal white text would be better to read rather than using any other subtle colours.

**Comment by TheEvilSkeleton** [comment]
I think we should merge this and improve the contrast in https://github.com/Vanilla-OS/website/pull/88.

**Comment by OpenSauce04** [comment]
It's worth noting that this PR exclusively addressed the logo graphics

**Comment by TheEvilSkeleton** [comment]
I apologize for making you wait, but we've merged https://github.com/Vanilla-OS/website/pull/92, which addresses this MR.

**Pull request closed without merging**
