### PR TITLE
Refactor Card component

### PR DESCRIPTION
**Pull request by mks-h**
The Card component practically has 4 copies of its content with minor variations, so I have started refactoring it.

### CODE REVIEW

**Comment by mks-h** [comment]
@mirkobrombin 

The "adv" type of Card uses a pair of `<h4>` and `<h2>` tags to divide a sentence. I believe this is a non-semantic use of headings that breaks the following usage notes from MDN:
>- Do not use heading elements to resize text. Instead, use the [CSS](https://developer.mozilla.org/en-US/docs/Glossary/CSS) [font-size](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size) property.
>- Do not skip heading levels: always start from \<h1>, followed by \<h2> and so on.

image

Other types of cards use `<h3>` tags. Given that both types are usually used at the same level, I think it is a good idea to use a single `<h3>` tag for both lines of "adv" card (using [`<br>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br) and [`::first-line`](https://developer.mozilla.org/en-US/docs/Web/CSS/::first-line) to achieve the same look). Is that alright with you?

Edit: The illustration doesn't actually use the Card component, but the point stands for both.

**Comment by mirkobrombin** [comment]
Mmh that looks an oversight by me. Yes, your solution is fine.

**Comment by mks-h** [comment]
There's some visual change with the new h3 adv cards, which I think is fine if not better:

### Old VS New

image image

image image

## In context:

### Old
image

### New:
image

### Old:
image

### New:
image

**Comment by mirkobrombin** [comment]
I like the new margins

**Comment by mks-h** [comment]
I have refactored the Card component to a certain degree. There's no immediate gain from it, apart from previously mentioned use of `h3` headings. Trying to improve it any further leads to more verbosity, so I'd like to stop here.

**Review by kbdharun — APPROVED** [review]

**Review by mirkobrombin — APPROVED** [review]

**Pull request merged**
