### PR TITLE
FAQ page

### LINKED ISSUE #27: Make a FAQ page
Make a FAQ page with the long list of questions, maybe divided into sections as needed. Keep a little FAQ section on the main page, with some first questions about the OS + a link to the FAQ page.

This will allow to send people to the FAQ first, so maybe we will get less questions about the manual partitioning and other highly requested features. It would also help to be able to link to a specific question.

Keeping all FAQs on the home page will be weird IMHO.

### PR DESCRIPTION
**Pull request by delight-aug**
This is how it looks at he moment:

image

Fixes #27

### CODE REVIEW

**Comment by delight-aug** [comment]
Well, the page is there and works alright. There's a link to it in the header, there's a button that leads there from the FAQ section on the home page. There are no anchor tags for specific questions, there are no question categories.

I say, this should be enough for now, because it's better to have FAQ sooner than later. Functional and visual improvements can be done later.

The only thing left before merging, is to actually populate it with questions.

**Comment by delight-aug** [comment]
I'd add the following:

Why is manual partitioning disabled?
There's no `apt` installed, how to install packages?
How to run a program installed with `apx`?
How do I install from AUR? (install the missing `base-devel` and `git` packages)
How to add or modify kernel parameters?

**Comment by delight-aug** [comment]
Visual commentary to the latest commit

https://user-images.githubusercontent.com/51861383/210181481-6a45413c-7fc8-4d5a-ae01-8ea3a17ac317.png
https://user-images.githubusercontent.com/51861383/210181482-917b5933-d78e-4dfa-9d44-a69d4134793f.png
https://user-images.githubusercontent.com/51861383/210181500-a23ec06e-2230-4be4-9f78-7b9e67c1f905.png

**Review by kbdharun — APPROVED** [review]
LGTM for now, I will send in some FAQs tomorrow.

**Comment by delight-aug** [comment]
I'd say this PR is ready to be merged. If you want to add more questions, this should be done in a separate PR. Considering Vanilla OS starts getting attention on YouTube, it's better to have a FAQ right now.

**Pull request merged**
