### PR TITLE
 Centered Title & Description

### PR DESCRIPTION
**Pull request by GabsEdits**

### CODE REVIEW

**Comment by mirkobrombin** [comment]
why the <sup2> tag? :eyes:

**Comment by GabsEdits** [comment]
What tag? 👀

**Comment by GabsEdits** [comment]
> why the <sup2> tag? :eyes: 

It looks nice :D

**Comment by mirkobrombin** [comment]
I don't see the difference :D

**Comment by GabsEdits** [comment]
Turns out that I was blind and thought it changed something... Just removed it

**Pull request merged**
